name: Leak Check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip libv8
        run: |
          files=$(find . -name "libv8*.zip")
          for file in $files; do
            dir=$(dirname "$file")  # Get the directory where the ZIP file is located
            echo "Extracting $file to directory $dir"
            unzip -o -d $dir $file
          done

      - name: Go Test
        env:
          CC: clang
          CXX: clang++
        run: |
          go test -c --tags leakcheck
          ./v8go.test
